/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClientHandle: typeof import('./src/components/locale/client-header/components/client-handle.vue')['default']
    ClientHeader: typeof import('./src/components/locale/client-header/index.vue')['default']
    ClientMenu: typeof import('./src/components/client-menu/index.vue')['default']
    ClientModal: typeof import('./src/components/client-modal/index.vue')['default']
    ClientProxyItems: typeof import('./src/components/client-proxy-items/index.vue')['default']
    ClientTable: typeof import('./src/components/client-table/index.vue')['default']
    ClientTableSearch: typeof import('./src/components/client-table-search/index.vue')['default']
    copy: typeof import('./src/components/client-table-search/index copy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
